apiVersion: v1
kind: Service
metadata:
  name: my-webapp-docker      
spec:
  selector:                  
    deploymentconfig: my-webapp-docker   
  ports:
  - name: 8080-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080      